// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djlxixdevertpwtsbglm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqbHhpeGRldmVydHB3dHNiZ2xtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMjI1MjcsImV4cCI6MjA2NDY5ODUyN30.S2MScN-XR0oYEtP2h-9XHY4J3y8yFAUL3MNyJgCQ0GY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);